<a href="https://colab.research.google.com/github/PoonamParkar/Breast_Cancer_prediction-End-to-end-ML-project/blob/main/U1W2_04_Numpy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Advanced Certification in AIML
## A Program by IIIT-H and TalentSprint
## Not For Grading

### Learning Objective

At the end of this experiment, you will be able to :

* Use Numpy Library

## Setup Steps

In [1]:
#@title Please enter your registration id to start: { run: "auto", display-mode: "form" }
Id = "2501553" #@param {type:"string"}


In [2]:
#@title Please enter your password (normally your phone number) to continue: { run: "auto", display-mode: "form" }
password = "8669320681" #@param {type:"string"}


In [3]:
#@title Run this cell to complete the setup for this Notebook
from IPython import get_ipython

ipython = get_ipython()

notebook= "U1W2_04_Numpy_Exercise" #name of the notebook
Answer = "Ungraded"
def setup():
#  ipython.magic("sx pip3 install torch")
    from IPython.display import HTML, display
    ipython.magic("sx wget https://cdn.iiith.talentsprint.com/aiml/Experiment_related_data/diabetes.csv")
    display(HTML('<script src="https://dashboard.talentsprint.com/submissions/record_ip.html?traineeId={0}&recordId={1}"></script>'.format(getId(),submission_id)))
    print("Setup completed successfully")
    return

def submit_notebook():

    ipython.magic("notebook -e "+ notebook + ".ipynb")

    import requests, json, base64, datetime

    url = "https://dashboard.talentsprint.com/xp/app/save_notebook_attempts"
    if not submission_id:
      data = {"id" : getId(), "notebook" : notebook, "mobile" : getPassword(), "batch" : ""}
      r = requests.post(url, data = data)
      r = json.loads(r.text)

      if r["status"] == "Success":
          return r["record_id"]
      elif "err" in r:
        print(r["err"])
        return None
      else:
        print ("Something is wrong, the notebook will not be submitted for grading")
        return None

    elif getComplexity() and getAdditional() and getConcepts() and getComments():
      f = open(notebook + ".ipynb", "rb")
      file_hash = base64.b64encode(f.read())

      data = {"complexity" : Complexity, "additional" :Additional,
              "concepts" : Concepts, "record_id" : submission_id,
              "id" : Id, "file_hash" : file_hash,
              "feedback_experiments_input" : Comments, "notebook" : notebook, "batch" : ""}

      r = requests.post(url, data = data)
      r = json.loads(r.text)
      if "err" in r:
        print(r["err"])
        return None
      else:
        print("Your submission is successful.")
        print("Ref Id:", submission_id)
        print("Date of submission: ", r["date"])
        print("Time of submission: ", r["time"])
        print("View your submissions: https://learn-iiith.talentsprint.com/notebook_submissions")
        # print("For any queries/discrepancies, please connect with mentors through the chat icon in LMS dashboard.")
      return submission_id
    else: submission_id


def getAdditional():
  try:
    if not Additional:
      raise NameError
    else:
      return Additional
  except NameError:
    print ("Please answer Additional Question")
    return None
def getComments():
  try:
    if not Comments:
      raise NameError
    else:
      return Comments
  except NameError:
    print ("Please answer Comments Question")
    return None

def getComplexity():
  try:
    if not Complexity:
      raise NameError
    else:
      return Complexity
  except NameError:
    print ("Please answer Complexity Question")
    return None

def getConcepts():
  try:
    if not Concepts:
      raise NameError
    else:
      return Concepts
  except NameError:
    print ("Please answer Concepts Question")
    return None

def getId():
  try:
    return Id if Id else None
  except NameError:
    return None

def getPassword():
  try:
    return password if password else None
  except NameError:
    return None

submission_id = None
### Setup
if getPassword() and getId():
  submission_id = submit_notebook()
  if submission_id:
    setup()

else:
  print ("Please complete Id and Password cells before running setup")


Setup completed successfully


## 1. Import the numpy package under the name np

Hint: import … as

In [4]:
# YOUR CODE HERE
import numpy as np

### 2. Print the numpy version and the configuration

Hint: `np.__version__`, `np.show_config()`

In [5]:
# YOUR CODE HERE
np.__version__

'2.0.2'

### 3. Create an array of 10 zeros

Hint:: np.zeros

In [9]:
# YOUR CODE HERE
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 4. Create an array of 10 zeros where the fifth element value is set to 1

Hint: array[4]

In [10]:
# YOUR CODE HERE
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 5. Create an array with values ranging from 10 to 49 (inclusive) and reverse it

Hint: arange

In [28]:
# YOUR CODE HERE
b = np.arange(10,50)
print(b)
b[::-1]
b[::-2]

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


array([49, 47, 45, 43, 41, 39, 37, 35, 33, 31, 29, 27, 25, 23, 21, 19, 17,
       15, 13, 11])

### 6. Find indices of non-zero elements from [1, 2, 0, 0, 4, 0]

Hint: np.nonzero

In [16]:
# YOUR CODE HERE
c = np.array([1, 2, 0, 0, 4, 0])
print(c)
np.nonzero(c)

[1 2 0 0 4 0]


(array([0, 1, 4]),)

### 7. Create a 3x3 identity matrix

Hint: np.eye

In [17]:
# YOUR CODE HERE
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 8. Create a 3x3x3 array with random values

Hint: np.random.random

In [25]:
# YOUR CODE HERE
np.random.random((3,3,3))
np.random.uniform(1,3, size=(3,3,3))

array([[[2.01004004, 2.61696188, 1.35112558],
        [1.54813924, 1.58631545, 2.81845094],
        [1.89613258, 2.92181431, 2.32471403]],

       [[1.61416118, 1.52635146, 2.28308293],
        [2.96873718, 2.88167881, 2.92802345],
        [1.6699349 , 1.73325471, 2.11646876]],

       [[2.53103165, 1.66794657, 2.30480513],
        [1.4529674 , 1.17777864, 1.76172927],
        [1.8745654 , 2.64908274, 1.96170623]]])

### 9. Create an array of all the even numbers from 30 to 70 (inclusive)

In [22]:
# YOUR CODE HERE
np.arange(30,71,2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

### 10. Generate 10x10 array with random integers between 0 to 4 (inclusive) and find the minimum and maximum values

Hint: min, max

In [31]:
# YOUR CODE HEREe
e = np.arange(0,5)
print(e)
print(e.min())
print(e.max())

[0 1 2 3 4]
0
4


### 11. Create a 5x5 matrix with values 1, 2, 3, 4 just below the diagonal

Hint: np.diag

In [27]:
# YOUR CODE HERE
np.diag([1,2,3,4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

### 12. Create an array with values ranging from 20 to 39 (inclusive). Calculate the square root of elements in it.

Hint: np.sqrt( )

In [37]:
# YOUR CODE HERE
f = np.arange(20,40)
print(f)
np.sqrt(f)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


array([4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ])

### 13. Transpose the given array [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
Hint: np.transpose()

In [40]:
# YOUR CODE HERE
g = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(g.T)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


### 14. Inverse the given array [[3, 4], [5, 6]]
Hint: np.linalg.inv()

In [41]:
# YOUR CODE HERE
k = np.array([[3, 4], [5, 6]])
np.linalg.inv(k)

array([[-3. ,  2. ],
       [ 2.5, -1.5]])

### 15. Concatenate two given arrays by columnwise (specify axis = 1)
Hint:  np.concatenate()

In [43]:
c = np.array([[1, 2],[3, 4]])
d = np.array([[5, 6],[7, 8]])

# YOUR CODE HERE

np.concatenate((c,d))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### 16. Transpose the given arrays and concatenate by columnwise (specify axis = 1)
Hint: np.concatenate()

In [44]:
a = np.array([[1,2],[3,4]])
d = np.array([[5,6],[7,8]])

# YOUR CODE HERE
np.concatenate((a.T,d.T))

array([[1, 3],
       [2, 4],
       [5, 7],
       [6, 8]])

### 17. For a given array, print second and third column


In [ ]:
a = np.array([[2, 4, 6, 8, 10],
              [3, 6, 9, 12, 15],
              [4, 8, 12, 16, 20]])

# YOUR CODE HERE


### 18. For a given array, print the values of the second and third rows from the second column.

In [46]:
a = np.array([[10, 11, 12, 13, 14],
               [15, 16, 17, 18, 19],
               [20, 21, 22, 23, 24],
               [25, 26, 27, 28, 29],
               [30, 31, 32, 33, 34]])

# YOUR CODE HERE
a[1:3,1]

array([16, 21])

### 19. For a given array perform the following:
#### 1. Calculate mean row wise and column wise by specifying respective axis
#### 2. What is the average value of array

In [50]:
# 2D array
array = np.array([[2, 4, 6, 8, 10],
                  [3, 6, 9, 12, 15],
                  [4, 8, 12, 16, 20]])

# YOUR CODE HERE
#array.mean(axis =0)
array.mean(axis =1)

array([ 6.,  9., 12.])

### 20. For a given array, get the slice of the first row from all the 3 matrices and print them.


In [52]:
a3 = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])

# YOUR CODE HERE
a3[:,0, :]

array([[10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

### Please answer the questions below to complete the experiment:




In [ ]:
#@title How was the experiment? { run: "auto", form-width: "500px", display-mode: "form" }
Complexity = "" #@param ["","Too Simple, I am wasting time", "Good, But Not Challenging for me", "Good and Challenging for me", "Was Tough, but I did it", "Too Difficult for me"]


In [ ]:
#@title If it was too easy, what more would you have liked to be added? If it was very difficult, what would you have liked to have been removed? { run: "auto", display-mode: "form" }
Additional = "" #@param {type:"string"}


In [ ]:
#@title Can you identify the concepts from the lecture which this experiment covered? { run: "auto", vertical-output: true, display-mode: "form" }
Concepts = "" #@param ["","Yes", "No"]


In [ ]:
#@title  Experiment walkthrough video? { run: "auto", vertical-output: true, display-mode: "form" }
Walkthrough = "" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]


In [ ]:
#@title  Text and image description/explanation and code comments within the experiment: { run: "auto", vertical-output: true, display-mode: "form" }
Comments = "" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]


In [ ]:
#@title Mentor Support: { run: "auto", vertical-output: true, display-mode: "form" }
Mentor_support = "" #@param ["","Very Useful", "Somewhat Useful", "Not Useful", "Didn't use"]


In [ ]:
#@title Run this cell to submit your notebook for Ungrading { vertical-output: true }
try:
  if submission_id:
      return_id = submit_notebook()
      if return_id : submission_id = return_id
  else:
      print("Please complete the setup first.")
except NameError:
  print ("Please complete the setup first.")